version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatgpt_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: bash -c "python init_db.py && uvicorn app:app --host 0.0.0.0 --port 8000"
    environment:
      - OPENAI_API_KEY=your-api-key-here
      - DATABASE_URL=postgresql+psycopg2://user:password@db/chatgpt_db
      - DEFAULT_USERS=user1:password1,user2:password2
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
