version: '3.8'

services:
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatgpt_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d chatgpt_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: api
    ports:
      - "8000:8000"
    command: bash -c "alembic upgrade head && uvicorn app.app:app --host 0.0.0.0 --port 8000"
    environment:
      - OPENAI_API_KEY=your-api-key-here
      - DATABASE_URL=postgresql+asyncpg://user:password@db/chatgpt_db
      - DEFAULT_USERS=user1:password1,user2:password2
      - USER_SECRET_PHRASE=SECRET
      - PYTHONPATH=/api
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
      - redis

  ui:
    build: ui
    ports:
      - "4200:4200"
    links:
      - api
